# Generated by Django 3.1.3 on 2020-11-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201129_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('publish', 'انتشار\u200cیافته'), ('archive', 'بایگانی\u200cشده')], default='draft', max_length=15, verbose_name='وضعیت انتشار'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='01.png', upload_to='articles/', verbose_name='تصویر شاخص'),
        ),
    ]
