# Generated by Django 3.1.3 on 2020-11-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201129_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='01.png', upload_to='articles/%y/%m/', verbose_name='تصویر شاخص'),
        ),
    ]
