# Generated by Django 3.1.3 on 2020-12-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=30, verbose_name='عنوان سایت')),
                ('instagram_page', models.URLField(verbose_name='صفحه اینستاگرام')),
                ('youtube_channel', models.URLField(verbose_name='کانال یوتیوب')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت سایت')),
            ],
        ),
    ]
