# Generated by Django 3.1.3 on 2020-12-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_page',
            field=models.URLField(blank=True, null=True, verbose_name='صفحه اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_channel',
            field=models.URLField(blank=True, null=True, verbose_name='کانال یوتیوب'),
        ),
    ]
