# Generated by Django 3.1.3 on 2020-12-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0002_auto_20201222_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'تنظیم', 'verbose_name_plural': 'تنظیم ها'},
        ),
    ]
